version: 0.0
os: ubuntu

files:
  - source: /
    destination: /apps/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root